name: Build Tailwind Minified CSS
on: [pull_request]

jobs:
  build-css:
    name: "build-css"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: |
          npm ci
          npm run build
          git add -A
          git config user.email "jessicadennis@gmail.com"
          git config user.name "Jessica Dennis"
          git commit -am "Generated minified CSS"
          git push
      - run: exit 0
