name: Build Tailwind Minified CSS
on: [pull_request]

jobs:
  prebuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: |
          npm ci
          npm run build
          git add -A
          git config user.email "jessicadennis@gmail.com"
          git config user.name "Jessica Dennis"
          git commit -am "Automated report"
          git push
