name: Build Tailwind Minified CSS
on: [pull_request]
env:
  GH_TOKEN: ${{ github.token }}

jobs:
  buildminified:
    permissions:
      actions: write
      contents: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - run: |
          npm ci
          npm run build
  commit-generated:
    permissions:
      actions: write
      contents: write
      checks: write
    runs-on: ubuntu-latest
    needs: ["buildminified"]
    steps:
      - run: |
          git add -A
          git config user.email "jessicadennis@gmail.com"
          git config user.name "Jessica Dennis"
          git commit -am "Minified CSS"
          git push
      - run: exit 0
